#7 Пакетное преобразование диалогов [TEST]
moevm/MSE-2023-core-vk_archive-24 pull request #18
Opened 2023-03-12 12:49 UTC by Luthineth

2023-03-12 14:59 UTC, Jengle88 approved these changes

2023-03-12 14:59 UTC, Jengle88 commented on vk_archive/src/jvmMain/kotlin/ui/mainWindow/MainWindowViewModel.kt
> +            counter += 1
counter++

2023-03-12 14:59 UTC, Jengle88 commented on vk_archive/src/jvmMain/kotlin/ui/mainWindow/MainWindowViewModel.kt
> +
Лишний дифф

2023-03-12 14:59 UTC, Jengle88 commented on vk_archive/src/jvmMain/kotlin/ui/mainWindow/MainWindowViewModel.kt
> +    fun goThroughDialogue(dialogueFolder: File): Int{
Вообще, по-хорошему, эти две функции в какой-нибудь другой файл закинуть... Они к части UI никакого отношения не имеют

2023-03-12 15:56 UTC, Luthineth commented on vk_archive/src/jvmMain/kotlin/ui/mainWindow/MainWindowViewModel.kt
> +    fun goThroughDialogue(dialogueFolder: File): Int{
это на время тут, я перенесу потом, конечно

2023-03-12 18:17 UTC, the21composer commented
Сортировка файлов (по убыванию номера messages{num}.html

2023-03-19 14:21 UTC, Jengle88 requested changes

2023-03-19 14:21 UTC, Jengle88 commented on vk_archive/src/jvmMain/kotlin/ui/mainWindow/MainWindowViewModel.kt
> +            if(item == dialogueFolder) continue
А зачем это? У тебя слева файл диалога, а справа - папка с диалогами

2023-03-19 15:27 UTC, Luthineth commented on vk_archive/src/jvmMain/kotlin/ui/mainWindow/MainWindowViewModel.kt
> +            if(item == dialogueFolder) continue
По факту, забыла убрать, когда меняла

2023-03-19 16:12 UTC, Jengle88 approved these changes

2023-03-19 19:02 UTC, merged