#8 Загрузка изображения из ВК по ссылке [DEV]
moevm/MSE-2023-core-vk_archive-24 pull request #35
Opened 2023-03-19 16:56 UTC by Luthineth

2023-03-19 18:10 UTC, Jengle88 requested changes

2023-03-19 18:10 UTC, Jengle88 commented on vk_archive/src/jvmMain/kotlin/utils/Utils.kt
> +fun reduceImageResolution(filePath: String, outputPath: String) {
Может лучше передавать параметры уменьшения? А то функция выглядит как-то урезано в плане функционала

2023-03-19 18:10 UTC, Jengle88 commented on vk_archive/src/jvmMain/kotlin/utils/Utils.kt
> +fun downloadImage(imageUrl: String, filePath: String) {
Лучше замени название функции на downloadImageJPG, чтобы было понятно, в каком расширении мы сохраняем фото

2023-03-25 18:05 UTC, Jengle88 commented
@Luthineth с какого коммита проверять?...

2023-03-25 18:13 UTC, Luthineth commented
@Jengle88 в тесте нормально показывается, зайди туда

2023-04-02 07:13 UTC, merged