#5 Перенос функциональности из репозитория DeelTer/VkDialogParser [DEV]
moevm/MSE-2023-core-vk_archive-24 pull request #42
Opened 2023-03-24 18:49 UTC by DmitrySergeev02

2023-03-25 12:43 UTC, Jengle88 commented
Нашёл баг - алгоритм неправильно работает в беседах. Вместо названия беседы выводит ФИ одного из участников. Но думаю его уже в другом ПР нужно будет фиксить

2023-03-25 17:44 UTC, Jengle88 commented
Также нужно уточнить, какой id нужно сохранять в диалоге. Потому что сейчас сохраняется id человека, а не диалога

2023-03-26 13:40 UTC, DmitrySergeev02 commented
Пофиксил баг с неправильным названием беседы

2023-03-26 22:24 UTC, Jengle88 requested changes

2023-03-26 22:24 UTC, Jengle88 commented on vk_archive/src/jvmMain/kotlin/utils/DialogJsonHelper.kt
> +        val file = File("${dir.absolutePath}/${dialog.id}.json")
Проблема - в dialog.id хранится путь к папке с диалогом, а не id

2023-03-26 22:24 UTC, Jengle88 commented on vk_archive/src/jvmMain/kotlin/utils/DialogJsonHelper.kt
> +    fun import(dir:File,ids:List<String>?):List<Dialog?>{
что такое dir и ids? Почему метод читает только по чему-то одному?

2023-03-28 17:10 UTC, Jengle88 approved these changes

2023-04-02 07:13 UTC, merged